.PHONY: install-adapter install-adapter bootstrap build

bootstrap: install-npm-modules install-adapter

install-npm-modules:
	npm install

install-adapter:
	npm i -D @sveltejs/adapter-static

build:
	npm run build